name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements_dev.txt
      - run: pip install -U pip
      - run: make init_dev
      - run: make test
